"""
Django settings for vaccination_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SERVER_ENV_FILE = Path("/var/www/secrets/.env")

# Production uses /var/www/secrets/.env on the server. For local fallback we
# still honor repo-level env files if the server file is not present.
if SERVER_ENV_FILE.exists():
    load_dotenv(SERVER_ENV_FILE, override=True)
else:
    for env_path in (BASE_DIR / ".env", BASE_DIR / ".env.production"):
        if env_path.exists():
            load_dotenv(env_path, override=True)


def require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise ValueError(f"{name} environment variable is missing!")
    return value

PATIENT_DATA_FERNET_KEY = require_env("PATIENT_DATA_FERNET_KEY")

# Ensure bytes
if isinstance(PATIENT_DATA_FERNET_KEY, str):
    PATIENT_DATA_FERNET_KEY = PATIENT_DATA_FERNET_KEY.encode()

CLINIC_DB_NAME = require_env("CLINIC_DB_NAME")
CLINIC_DB_USER = require_env("CLINIC_DB_USER")
CLINIC_DB_PASSWORD = require_env("CLINIC_DB_PASSWORD")
CLINIC_DB_HOST = require_env("CLINIC_DB_HOST")
CLINIC_DB_PORT = os.getenv("CLINIC_DB_PORT", "3306")

MASTERS_DB_NAME = require_env("MASTERS_DB_NAME")
MASTERS_DB_USER = require_env("MASTERS_DB_USER")
MASTERS_DB_PASSWORD = require_env("MASTERS_DB_PASSWORD")
MASTERS_DB_HOST = require_env("MASTERS_DB_HOST")
MASTERS_DB_PORT = os.getenv("MASTERS_DB_PORT", "3306")

PATIENTS_DB_NAME = require_env("PATIENTS_DB_NAME")
PATIENTS_DB_USER = require_env("PATIENTS_DB_USER")
PATIENTS_DB_PASSWORD = require_env("PATIENTS_DB_PASSWORD")
PATIENTS_DB_HOST = require_env("PATIENTS_DB_HOST")
PATIENTS_DB_PORT = os.getenv("PATIENTS_DB_PORT", "3306")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7r1gry17%^l63tjrxwl&8&@7ccl#vagkax(-k)y=z-(#e(pv-@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "newvaccine.cpdinclinic.co.in",]  # dev
CSRF_TRUSTED_ORIGINS = [
    "http://newvaccine.cpdinclinic.co.in",
    "https://newvaccine.cpdinclinic.co.in"
]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'vaccinations.apps.VaccinationsConfig',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vaccination_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vaccination_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': CLINIC_DB_NAME,
        'USER': CLINIC_DB_USER,
        'PASSWORD': CLINIC_DB_PASSWORD,
        'HOST': CLINIC_DB_HOST,
        'PORT': CLINIC_DB_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            "init_command": "SET NAMES 'utf8mb4'"
       },
    },
    'masters': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MASTERS_DB_NAME,
        'USER': MASTERS_DB_USER,
        'PASSWORD': MASTERS_DB_PASSWORD,
        'HOST': MASTERS_DB_HOST,
        'PORT': MASTERS_DB_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            "init_command": "SET NAMES 'utf8mb4'"
        },
    },
    'patients': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': PATIENTS_DB_NAME,
        'USER': PATIENTS_DB_USER,
        'PASSWORD': PATIENTS_DB_PASSWORD,
        'HOST': PATIENTS_DB_HOST,
        'PORT': PATIENTS_DB_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            "init_command": "SET NAMES 'utf8mb4'"
        },
    },
}

DATABASE_ROUTERS = ['vaccinations.routers.MasterPatientRouter']
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ...existing code...
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA (for doctor photo upload)

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_SECURE = False  # dev only
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'   # default is already Lax, make it explicit
SESSION_SAVE_EVERY_REQUEST = True

# Keep cookies sent on the top-level Google redirect back to your app.
SESSION_COOKIE_SAMESITE = "Lax"   # default is already Lax, make it explicit
SESSION_COOKIE_SECURE = True     # dev only
LOGIN_URL = "/auth/google/start/"

# ---- Google OAuth (read secrets from .env file only) ----
GOOGLE_CLIENT_ID = require_env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = require_env("GOOGLE_CLIENT_SECRET")
GOOGLE_OAUTH_REDIRECT_URI = require_env("GOOGLE_OAUTH_REDIRECT_URI").strip()
GOOGLE_OAUTH_REDIRECT_PATH = urlparse(GOOGLE_OAUTH_REDIRECT_URI).path or "/auth/google/callback/"

GOOGLE_OAUTH = {
    "CLIENT_ID": GOOGLE_CLIENT_ID,
    "CLIENT_SECRET": GOOGLE_CLIENT_SECRET,
    "AUTH_URL": "https://accounts.google.com/o/oauth2/v2/auth",
    "TOKEN_URL": "https://oauth2.googleapis.com/token",
    "USERINFO_URL": "https://www.googleapis.com/oauth2/v2/userinfo",
    "REDIRECT_URI": GOOGLE_OAUTH_REDIRECT_URI,
    "SCOPES": ["openid", "email", "profile"],
}

MEDIA_ROOT = BASE_DIR / "media"
AUTO_SEND_TO_PARENT_ON_ADD = True
# at bottom
MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
PHONE_HASH_SALT = require_env("PHONE_HASH_SALT")
SEARCH_PEPPER = require_env("SEARCH_PEPPER")
